# Generated by Django 4.1.1 on 2024-09-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_rename_categories_categorie_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='products_of_categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.categorie'),
        ),
    ]
